pull_request_rules:
  - name: automatic merge for Dependabot pull requests
    conditions:
      - author=dependabot[bot]
      - check-success=build
      - 'title~=\(deps-dev\): bump '
    actions:
      merge:
        method: squash
